version: '3'
services:
  #JupyterLab will be available at port 9888
  clx:
    build: .
    ports:
      - "9888:8888"
      - "9787:8787"
      - "9686:8686"
    stdin_open: true
    tty: true
    runtime: nvidia
      - /mnt/data:/rapids/host/notebooks/host/data
      - /home/ubuntu/notebooks:/rapids/notebooks/host
  rapidsdev:
    image: rapidsai/rapidsai-dev:0.16-cuda11.0-devel-centos7-py3.8
    ports: 
      - "8888:8888"
      - "8787:8787"
      - "8686:8686"
    stdin_open: true
    tty: true
    runtime: nvidia
    volumes:
      - /mnt/data:/rapids/host/notebooks/host/data
      - /home/ubuntu/notebooks:/rapids/notebooks/host
